### ISSUE TITLE
Unable to use Props and States with maps and slices

### ISSUE THREAD

**Issue by aandryashin** [myitcv/react#133]
Generate minimal app with
```
reactGen -init minimal
```
Add the following code to app.go
```
type AppState struct {
        m map[string]string
}

type AppProps struct {
        m []string
}
```
Regenerate code
```
go generate
```
Try to build app
```
go build
./gen_App_reactGen.go:50:11: invalid operation: a == val.(AppState) (struct containing map[string]string cannot be compared)
./gen_App_reactGen.go:64:11: invalid operation: a == val.(AppProps) (struct containing []string cannot be compared)
```

I can confirm that using ```reflect.DeepEqual(b, val)``` fixes the issue.

**Comment by myitcv** [comment]
@aandryashin great question. 

This is effectively by design, because [slice, map and function values are not comparable](https://golang.org/ref/spec#Comparison_operators) and the generated code uses comparison of the state or props struct values to determine whether the state or props respectively have changed.

This is where `myitcv.io/react` is more strict than React; more precisely, its behaviour is akin to [`React.PureComponent`](https://reactjs.org/docs/react-api.html#reactpurecomponent).

Three options for fixing this:

* define an `Equals` method on the state and props types ([example](https://github.com/myitcv/react/blob/c130998bb41bc4a8a1843eb48210ab057a62e676/examples/todoapp/todo_app.go#L32)). This is my least favourite option, and I have toyed with removing support for this in the past because it will end up just slowing down your app
* make the field types comparable (e.g. `*map[string]string`)
* use immutable types ([example](https://github.com/myitcv/react/blob/c130998bb41bc4a8a1843eb48210ab057a62e676/examples/immtodoapp/todo_app.go#L26))

**Comment by aandryashin** [comment]
Thanks, got it!
