### ISSUE TITLE
can not use input type="text"

### ISSUE THREAD

**Issue by lijianying10** [myitcv/react#155]
There is something wrong with my project.

```
func (a SampleDef) Render() react.Element {
	return react.Div(nil,
		react.Input(&react.InputProps{
			Type: "text",
		}),
	)
}
```

It seems generated 

```
<div><input type="text" aria-expanded="false" aria-haspopup="false" aria-labelledby="" class="" placeholder="" role="" value=""></div>
```

1. Why so many no use attribute under input tag.
2. can not input anything and don't work with chrome.

**Comment by myitcv** [comment]
Hi @lijianying10 

In order to "bind" a text input, you need to set the `Value` and `OnChange` fields on the `InputProps`.

The simplest example of this (that happens to use a `<textarea>` but it's identical in approach) is:

https://blog.myitcv.io/gopherjs_examples_sites/markdowneditor/

The relevant bit of source code is:

https://github.com/myitcv/react/blob/57b167914d27bc71eafc5447e5bf54dacb2a22a4/examples/markdowneditor/markdown_editor.go#L50-L54

That explains why you can't input anything.

> Why so many no use attribute under input tag.

This is as a result of [zero values](https://golang.org/ref/spec#The_zero_value) for those properties. Unlike JavaScript, if, for example, a field is of type `bool`, Go has a zero value of `false` (in JavaScript it would be `undefined`). For a `string` field the zero value is `""`. Hence when we come to render elements, you will often see the zero value being "set" in such fields, even if you haven't set a value yourself. There should be no impact/problems as a result, but please say if there is (there are some edge cases where we do need to distinguish a field having been set or not).

---

I'm going to close this issue for now because I think the markdown example should answer your main query, but please re-open in case you need to.
