### ISSUE TITLE
Update Components Across Go Packages

### ISSUE THREAD

**Issue by norunners** [myitcv/react#68]
Hello, I have encountered an issue while trying to update components across Go packages. Using the same code that renders successfully in the same Go package causes a frozen render when broken to two separate Go packages. This may be an infinite loop.

Here are is the sample code to reproduce the success and fail cases, just go get and run gopherjs serve on the root package with main.
Pass: https://github.com/norunners/helloreact/tree/def-pass
Fail: https://github.com/norunners/helloreact/tree/def-fail

I observed the same behavior from passing the callback behavior as Props.
Pass: https://github.com/norunners/helloreact/tree/props-pass
Fail: https://github.com/norunners/helloreact/tree/props-fail

**Comment by myitcv** [comment]
Thanks for raising this here @norunners - as I mentioned in the Slack channel, I will take a look when I get a minute and revert back.

**Comment by norunners** [comment]
Sounds good, I cut this issue for transparency in case other folks encounter the same issue.

**Comment by myitcv** [comment]
This appears to be a GopherJS compiler issue... because after a cursory glance it doesn't even start running `main`...

**Comment by myitcv** [comment]
@norunners this is actually related to https://github.com/gopherjs/gopherjs/issues/414

For the two branches where you see things "failing" the code does not actually compile because of an import cycle. If you run `go build` in your `main` package you'll see something like:

```
import cycle not allowed
package github.com/norunners/helloreact
        imports github.com/norunners/helloreact/app
        imports github.com/norunners/helloreact/nav
        imports github.com/norunners/helloreact/app
```

`gopherjs serve` doesn't report the problem; like `gopherjs build` it should (but doesn't because of the linked issue).

Also, as far as updating components in different packages is concerned, I don't think there's any issues there, no least because [the examples showcase](https://github.com/myitcv/react/blob/master/examples/examples.go) does this repeatedly. 

So I'd be tempted to close this issue... but will wait to hear back from you first.

**Comment by norunners** [comment]
Thank you for investigating this, if this is the case we can put an extra gotcha in the docs about circular dependencies. 

Tonight, I'll do a quick proof of concept of putting the callback behavior interface in a third "share" Go package to verify that is the root cause.

**Comment by myitcv** [comment]
> Thank you for investigating this, if this is the case we can put an extra gotcha in the docs about circular dependencies.

No problem.

Sorry if I wasn't clear in my previous message. It's not a gotcha (with the React bindings); it's a bug in GopherJS that the circular dependency isn't reported to you as an error in your code.

**Comment by norunners** [comment]
Works as expected! As you mentioned in the related issue, this is something gopherjs serve should surface as an error. Feel free to close this issue.

**Comment by myitcv** [comment]
Great. Closing this issue therefore
