### ISSUE TITLE
table tags

### ISSUE THREAD

**Issue by GingaNinja** [myitcv/react#97]
can we have tables and associated tags?

**Comment by myitcv** [comment]
@GingaNinja certainly can. It's "just" a case of adding the definitions. 

I do have plans to code generate all definitions from the HTML 5 spec, but for now the definitions are crafted by hand with code generator support (where "definitions" is defined as elements and their respective attributes).

I'll put together a quick PR for the obvious elements like `<table>`, `<tr>` and `<td>` along with a wiki outlining the steps I followed so that hopefully others can help contribute the missing pieces.

**Comment by GingaNinja** [comment]
thanks @myitcv , I did actually start looking at how to do it, and at least managed to add the table tag, so if I beat you to it, are you taking contributions?

**Comment by myitcv** [comment]
Absolutely!

**Comment by myitcv** [comment]
@GingaNinja - please take a look at https://github.com/myitcv/react/pull/99 which I've just merged for an example of how to add additional elements.

**Comment by myitcv** [comment]
This has been done via #137 and #141.
